apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc-homeapp-dev
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8180
  selector:
    app: label-pod-homeapp-dev-aks
    
